blueprint:
  name: Better Thermostat Heating mode
  description: Set BT Thermostats to Heating mode if Schedule event is active.
  domain: automation
  source_url: https://github.com/KartoffelToby/better_thermostat/blob/master/blueprints/heating_mode.yaml
  input:
    heating_times_schedule:
      name: Schedule helper
      selector:
        entity:
          domain: schedule

    thermostat_target:
      name: Thermostats
      selector:
        target:
          device:
            integration: better_thermostat
          entity:
            integration: better_thermostat
            domain: climate

    night_temp:
      name: Heating Temperature
      description: The target temperature for heating
      default: 22
      selector:
        number:
          min: 5
          max: 35
          unit_of_measurement: °C

mode: queued
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input heating_times_schedule
    from: "off"
    to: "on"
  - platform: state
    entity_id: !input heating_times_schedule
    from: "on"
    to: "off"
condition: []
action:
  - if:
      - condition: state
        entity_id: !input heating_times_schedule
        state: "off"
    then:
      - service: better_thermostat.set_temp_target_temperature
        data:
          temperature: !input night_temp
        target: !input thermostat_target
    else:
      - service: better_thermostat.restore_saved_target_temperature
        data: {}
        target: !input thermostat_target
